# Generated by Django 3.1.7 on 2021-04-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzeria', '0040_auto_20210405_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pizzeria.price',),
        ),
    ]
