# Generated by Django 3.1.7 on 2021-02-27 18:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzauser',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='pizzauser',
            name='tg_id',
        ),
        migrations.RemoveField(
            model_name='pizzauser',
            name='tg_name',
        ),
        migrations.AddField(
            model_name='pizzauser',
            name='language',
            field=models.CharField(choices=[('UK', 'Ukrainian'), ('RU', 'Russian'), ('EN', 'English')], default='UK', max_length=2),
        ),
        migrations.AddField(
            model_name='pizzauser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pizzauser',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='viber',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
