# Generated by Django 3.1.7 on 2021-02-27 19:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='contact_tg',
            new_name='contact_telegram',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='contact_tg_id',
            new_name='contact_telegram_id',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='fb_link',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='tg_link',
            new_name='telegram_link',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=100000, null=True)),
                ('image', models.ImageField(blank=True, default='static/food.png', null=True, upload_to='categories_images/', verbose_name='Image')),
                ('is_published', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='unicode_title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='pizzeria.category')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
            },
        ),
    ]
