# Generated by Django 3.1.7 on 2021-02-28 12:32

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_auto_20210227_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='support',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(default='support@example.com', max_length=254, verbose_name='Support email'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_name',
            field=models.CharField(max_length=120, verbose_name='Size name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_unit',
            field=models.CharField(max_length=30, verbose_name='Size unit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='pizzeria.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='about',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='language',
            field=models.CharField(choices=[('UK', 'Ukrainian'), ('RU', 'Russian'), ('EN', 'English')], default='UK', max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='telegram id'),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='telegram name'),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='viber',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='viber'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_about_text',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Contact about text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='support@example.com', max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact telegram id'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_viber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact viber'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact about text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Github Link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Map coordinates'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Contact phone number'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number_two',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Second contact phone number'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='pizza', max_length=40, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube link'),
        ),
    ]
