# Generated by Django 3.1.7 on 2021-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0005_auto_20210228_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzauser',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('ru', 'Russian'), ('en', 'English')], default='uk', max_length=2, verbose_name='language'),
        ),
    ]
