# Generated by Django 3.1.7 on 2021-02-28 14:52

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0006_auto_20210228_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_about_text',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_about_text_en',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Contact about text English'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_about_text_ru',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Contact about text Russian'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_about_text_uk',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Contact about text Ukrainian'),
        ),
    ]
