# Generated by Django 3.1.7 on 2021-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0007_auto_20210228_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Size name'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Size name'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_name_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Size name'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_unit_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Size unit'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_unit_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Size unit'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_unit_uk',
            field=models.CharField(max_length=30, null=True, verbose_name='Size unit'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_en',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ru',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_uk',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='food',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='food',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='food',
            name='title_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
    ]
