# Generated by Django 3.1.7 on 2021-02-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0009_auto_20210228_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_vegeterian',
            field=models.BooleanField(default=False, verbose_name='Is vegeterian'),
        ),
    ]
