# Generated by Django 3.1.7 on 2021-03-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0010_food_is_vegeterian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'ordering': ['value'],
            },
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_vegeterian',
        ),
        migrations.AddField(
            model_name='food',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Is vegetarian'),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='pizzeria.category', verbose_name='Category')),
                ('food', models.ManyToManyField(related_name='users_who_passed_test', through='pizzeria.Price', to='pizzeria.Food')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.food'),
        ),
        migrations.AddField(
            model_name='price',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.size'),
        ),
    ]
