# Generated by Django 3.1.7 on 2021-03-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0012_auto_20210304_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterField(
            model_name='price',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.food', verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.size', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='size',
            name='food',
            field=models.ManyToManyField(related_name='sizes', through='pizzeria.Price', to='pizzeria.Food', verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Value'),
        ),
    ]
