# Generated by Django 3.1.7 on 2021-03-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0014_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Currency symbol'),
        ),
    ]
