# Generated by Django 3.1.7 on 2021-03-04 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0015_sitesettings_currency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Created'), (1, 'Accepted'), (2, 'Ready'), (3, 'Delivery'), (4, 'Given')], default=0, verbose_name='status')),
                ('paid', models.BooleanField(verbose_name='Paid')),
                ('finished', models.BooleanField(verbose_name='Finished')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('addon', models.ManyToManyField(related_name='order_items', to='pizzeria.Addon', verbose_name='Addon')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='pizzeria.food', verbose_name='Food')),
                ('food_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='half_order_item', to='pizzeria.food', verbose_name='Food two')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pizzeria.order', verbose_name='Order item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzeria.size', verbose_name='Size')),
            ],
        ),
        migrations.AddField(
            model_name='addon',
            name='order_item',
            field=models.ManyToManyField(related_name='addons', to='pizzeria.OrderItem', verbose_name='Order Item'),
        ),
    ]
