# Generated by Django 3.1.7 on 2021-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0017_auto_20210304_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
    ]
