# Generated by Django 3.1.7 on 2021-03-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0018_auto_20210304_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='addon',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_items', to='pizzeria.Addon', verbose_name='Addon'),
        ),
    ]
