# Generated by Django 3.1.7 on 2021-03-11 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0021_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address english'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address russian'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address ukrainan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
