# Generated by Django 3.1.7 on 2021-03-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0022_auto_20210311_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='map link'),
        ),
    ]
