# Generated by Django 3.1.7 on 2021-03-11 19:41

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0023_sitesettings_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_en_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address english'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address english'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address english'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_about_text_en_en',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Contact about text English'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_about_text_en_ru',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Contact about text English'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_about_text_en_uk',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Contact about text English'),
        ),
    ]
