# Generated by Django 3.1.7 on 2021-03-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0025_auto_20210311_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('title_uk', models.CharField(max_length=120, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description')),
                ('description_uk', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, default='static/food.png', null=True, upload_to='categories_images/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slides', to='pizzeria.food', verbose_name='Food')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
