# Generated by Django 3.1.7 on 2021-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0028_auto_20210313_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol_en',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Currency symbol'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol_ru',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Currency symbol'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol_uk',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Currency symbol'),
        ),
    ]
