# Generated by Django 3.1.7 on 2021-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0029_auto_20210313_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Size name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Size name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_name_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Size name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_name_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Size name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_unit',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Size unit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_unit_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Size unit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_unit_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Size unit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_unit_uk',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Size unit'),
        ),
    ]
