# Generated by Django 3.1.7 on 2021-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0030_auto_20210314_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
    ]
