# Generated by Django 3.1.7 on 2021-03-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0031_auto_20210314_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_on_front',
            field=models.BooleanField(default=False, verbose_name='Is on front'),
        ),
    ]
