# Generated by Django 3.1.7 on 2021-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0032_food_is_on_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_on_front',
            field=models.BooleanField(default=False, verbose_name='Is on front'),
        ),
    ]
