# Generated by Django 3.1.7 on 2021-03-25 16:10

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0033_category_is_on_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_categories_text',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='menu categories text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_categories_text_en',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='menu categories text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_categories_text_ru',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='menu categories text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_categories_text_uk',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='menu categories text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pizza_menu_text',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='pizza text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pizza_menu_text_en',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='pizza text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pizza_menu_text_ru',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='pizza text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pizza_menu_text_uk',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='pizza text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reservation_text',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='reservation text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reservation_text_en',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='reservation text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reservation_text_ru',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='reservation text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reservation_text_uk',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='reservation text'),
        ),
    ]
