# Generated by Django 3.1.7 on 2021-03-26 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0034_auto_20210325_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='pizzeria.food', verbose_name='Food'),
        ),
    ]
