# Generated by Django 3.1.7 on 2021-03-26 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0035_auto_20210326_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.food', verbose_name='Food'),
        ),
    ]
