# Generated by Django 3.1.7 on 2021-03-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0036_auto_20210326_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='order_item',
        ),
    ]
