# Generated by Django 3.1.7 on 2021-03-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0037_remove_addon_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_it_for_kids',
            field=models.BooleanField(default=False, verbose_name='For kids'),
        ),
    ]
