# Generated by Django 3.1.7 on 2021-04-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0038_food_is_it_for_kids'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('food', 'size')},
        ),
    ]
