name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd pizzeria
            git pull
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            echo 'Deployment successful'



#name: remote ssh command
#on: [push]
#jobs:
#
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#    - name: executing remote ssh commands using password
#      uses: fifsky/ssh-action@master
#      with:
#          command: |
#            cd pizzeria
#            git pull
#            sudo systemctl restart gunicorn
#            sudo systemctl restart nginx
#            echo 'Deployment successful'
#          host: ${{ secrets.SSH_HOST }}
#          user: ${{ secrets.SSH_USERNAME }}
#          pass: ${{ secrets.SSH_PASSWORD }}
#          args: -tt
